apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhtml-deploy
spec:
  selector:
    matchLabels:
      app: myhtml
  template:
    metadata:
      labels:
        app: myhtml
    spec:
      containers:
      - name: myhtml-container
        image: docker.io/kamal0405/test-html-cicd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myhtml-service
spec:
  selector:
    app: myhtml
  ports:
  - port: 8080
    targetPort: 8080


